/**
 *  Emoji Extension for ktMarkDown.js
 *    by Kengo Tsuruzono ( crane@sitearo.com )
 */

	'use strict';

	function Emoji() {
	}

	///// EMOJI /////
	Emoji.prototype.emojis = {

		// PEOPLE

			bowtie							: '',
			smile							: '😄',
			laughing						: '😆',
			blush							: '😊',
			smiley							: '😃',
			relaxed							: '☺',
			smikr							: '😏',
			heart_eyes						: '😍',
			kissing_heart					: '😘',
			kissing_closed_eyes				: '😚',
			flushed							: '😳',
			relieved						: '😌',
			satisfied						: '😆',
			grin							: '😁',
			wink							: '😉',
			stuck_out_tongue_winking_eye	: '😜',
			stuck_out_tongue_closed_eye		: '😝',
			grinning						: '',
			kissing							: '😗',
			kissing_smiling_eyes			: '😙',
			stuck_out_tongue				: '😛',
			sleeping						: '😴',
			worried							: '😟',
			frowing							: '😦',
			grimacing						: '',
			confused						: '',
			hushed							: '',
			expressionless					: '',
			unamused						: '',
			sweat_smile						: '😅',
			sweat 							: '😓',
			disappointed_relieved 			: '😥',
			weary 							: '😩',
			pensive 						: '😔',
			disappointed 					: '😞',
			confounded 						: '😖',
			fearful							: '😨',
			cold_sweat						: '😰',
			persevere						: '😣',
			cry 							: '😢',
			sob 							: '😭',
			joy 							: '😂',
			astonished 						: '😲',
			scream 							: '😱',
			neckbeard 						: '',
			tired_face 						: '😫',
			angry 							: '😠',
			rage 							: '😡',
			triumph							: '',
			sleepy 							: '😪',
			yum 							: '😋',
			mask 							: '😷',
			sunglasses 						: '',
			dizzy_face 						: '',
			imp								: '👿',
			smiling_imp 					: '',
			neutral_face					: '',
			no_mouth 						: '',
			innocent 						: '',
			alien 							: '👽',

			yellow_heart 					: '💛',
			blue_heart 						: '💙',
			purple_heart 					: '💜',
			heart 							: '❤',
			green_heart 					: '💚',
			broken_heart 					: '💔',
			heartbeat 						: '💓',
			heartpulse	 					: '💗',
			two_heart						: '💛',
			revolving_heart					: '💛',
			cupid 							: '💘',
			sparkling_heart					: '',


			speech_balloon 		: '',

		// HANDS

			'+1'				: '👍',
			'thumbsup'			: '👍',
			'-1'				: '👎',
			'thumbsdown'		: '👎',
			'ok_hand'			: '👌',
			'punch'				: '👊',
			'fist'				: '✊',
			'v'					: '✌',
			'wave'				: '👋',
			'hand'				: '✋',
			'raised_hand'		: '✋',
			'open_hands'		: '👐',
			'point_up'			: '👆',
			'point_down'		: '👇',
			'point_right'		: '👉',
			'point_left'		: '👈',
			'raised_hands'		: '🙌',
			'pray'				: '🙏',
			'point_up_2'		: '☝',
			'clap'				: '👏',
			'muscle'			: '💪',

		// OBJECTS

			bamboo				: '🎍',
			gift_heart			: '💝',
			dolls				: '🎎',

			school_satchel		: '🎒',
			mortar_board		: '🎓',
			flags				: '🎏',

			fireworks			: '🎆',
			sparkler			: '🎇',
			wind_chime			: '🎐',

			sunny				: '☀',
			umbrella			: '☔',
			cloud				: '☁',
			snowflake			: '',
			snowman				: '⛄',
			zap					: '⚡',
			cyclone				: '🌀',

			foggy				: '',
			ocean				: '',

		// MACHINES

			cd 					: '💿',
			dvd 				: '📀',
			floppy_disk 		: '💾',
			camera 				: '📷',
			video_camera 		: '📹',
			movie_camera		: '🎥',
			computer 			: '💻',
			tv 					: '📺',
			iphone 				: '📱',
			phone 				: '☎️',
			telephone 			: '☎️',
			telephone_receiver 	: '📞',
			pager 				: '📟',
			fax 				: '📠',
			minidisc 			: '💽',
			vhs 				: '📼',
			sound 				: '🔊',
			speaker 			: '🔊',
			mute 				: '',
			loudspeaker 		: '📢',
			mega 				: '📣',
			hourglass 			: '⌛️',
			hourglass_flowing_sand : '⏳️',
			alram_clock 		: '⏰',
			watch 				: '⌚️',
			radio 				: '📻',
			satellite 			: '📡',
			loop 				: '➿',
			mag 				: '🔍',
			mag_right 			: '🔎',
			unlock 				: '🔓',
			lock 				: '🔒',
			lock_with_ink_pen 	: '🔏',
			closed_lock_with_key : '🔐',
			key 				: '🔑',
			bulb 				: '💡',
			flashlight 			: '🔦',
			high_brightness 	: '🔆',
			low_brightness 		: '🔅',
			electric_plug 		: '🔌',
			battery 			: '🔋',
			calling 			: '📲',
			email 				: '📩',
			mailbox 			: '📫',
			postbox 			: '📮',
			bath 				: '🛀',
			bathtub 			: '🛁',
			shower 				: '🚿',
			toilet 				: '🚽',
			wrench 				: '🔧',
			nut_and_bolt		: '🔩',
			hammer 				: '🔨',
			seat 				: '💺',

		// MONEY

			moneybag 			: '💰',
			yen					: '💴',
			doller 				: '💵',
			pound 				: '💷',
			euro 				: '💶',
			credit_card 		: '💳',
			money_with_wings	: '💸',

		// ANIMALS & PLANTS

			cat					: '🐱',
			dog					: '🐶',
			mouse				: '🐭',
			hamster				: '🐹',
			rabbit				: '🐰',
			wolf				: '🐺',
			frog				: '🐸',
			tiger				: '🐯',
			koala				: '🐨',
			bear 				: '🐻',
			pig 				: '🐷',
			pig_nose			: '🐽',
			cow 				: '🐮',
			boar 				: '🐗',
			monkey_face 		: '🐵',
			monkey 				: '🐒',
			horse 				: '🐴',
			racehorse 			: '🐎',
			camel 				: '🐪',
			sheep				: '🐑',
			elephant 			: '🐘',
			panda_face			: '🐼',
			snake 				: '🐍',
			bird 				: '🐦',
			baby_chick 			: '🐤',
			hatched_chick 		: '🐥',
			hatching_chick 		: '🐣',
			chiken 				: '🐔',
			penguin 			: '🐧',
			turtle 				: '🐢',
			bug 				: '🐛',
			honeybee 			: '🐝',
			ant 				: '🐜',
			beetle 				: '🐞',
			snail 				: '🐌',
			octopus 			: '🐙',
			tropical_fish 		: '🐠',
			fish 				: '🐟',
			whale 				: '🐳',
			whale2 				: '🐋',
			dolphin 			: '🐬',
			cow2 				: '🐄',
			ram 				: '🐏',
			rat 				: '🐀',
			water_buffalo 		: '🐃',
			tiger2 				: '🐅',
			rabbit2 			: '🐇',
			dragon 				: '🐉',
			goat 				: '🐐',
			rooster 			: '🐓',
			dog2 				: '🐕',
			pig2 				: '🐖',
			mouse2 				: '🐁',
			ox 					: '🐂',
			dragon_face			: '🐲',
			blowfish 			: '🐡',
			crocodile 			: '🐊',
			dromedary_camel 	: '🐫',
			leopard 			: '🐆',
			cat2 				: '🐈',
			poodle 				: '🐩',
			paw_prints 			: '🐾',
			bouquet 			: '💐',
			cherry_blossom		: '🌸',
			tulip 				: '🌷',
			four_leaf_clover	: '🍀',
			rose 				: '🌹',
			sunflower 			: '🌻',
			hibiscus 			: '🌺',
			maple_leaf			: '🍁',
			leaves 				: '🍃',
			fallen_leaf 		: '🍂',
			herb 				: '🌿',
			mushroom 			: '🍄',
			cactus 				: '🌵',
			palm_tree 			: '',
			evergreen_tree 		: '🌲',
			deciduous_tree 		: '🌳',
			chestnut 			: '🌰',
			seedling 			: '',
			blossom 			: '',
			ear_of_rice 		: '🌾',
			shell 				: '🐚',


		// SPORTS

			football			: '🏈',
			basketball			: '🏀',
			soccer				: '⚽',
			baseball			: '⚾',
			tennis				: '🎾',
			'8ball'				: '🎱',

			warning				: '⚠',
			construction		: '🚧',
			beginner			: '🔰',
			atm					: '🏧',

			dart				: '🎯',
			mahjong				: '🀄',


		// FOODS

			coffee				: '☕',
			tea					: '🍵',
			sake				: '🍶',
//			baby_buttle			: '',
			beer				: '🍺',
			beers				: '🍻',
			cocktail			: '🍸',
			fork_and_knife		: '🍴',
//			pizza				: '',
			hamburger			: '🍔',
			fries				: '🍟',
//			poultry_leg			: '',
//			meat_on_bone		: '',
			spagetti			: '🍝',
			curry				: '🍛',
//			fried_shrimp		: '',
			bento				: '🍱',
			sushi				: '🍣',
//			fish_cake			: '',
			rice_ball			: '🍙',
			rice_cracker		: '🍘',
			rice 				: '🍚',
			ramen				: '🍜',
			stew				: '🍲',
			oden				: '🍢',
			dango				: '🍡',
			egg					: '🍳',
			bread				: '🍞',
//			doughnut			: '🍞',
//			custard				: '🍞',
			icecream			: '🍦',
//			ice_cream			: '🍧',
			shaved_ice			: '🍧',
			birthday			: '🎂',
			cake				: '🍰',
//			cookie				: '🍰',
//			chocolate_bar		: '🍰',
//			candy				: '🍰',
//			lollipop			: '🍰',
//			honey_pot			: '🍰',
			apple				: '🍎',
			tangeline			: '🍊',
//			lemon				: '🍊',
//			cherries			: '🍊',
//			grapes				: '🍊',
			watermelon			: '🍉',
			strawberry			: '🍓',
//			peach				: '🍓',
//			melon				: '🍓',
//			banana				: '🍓',
//			pear				: '🍓',
//			pinapple			: '🍓',
//			sweet_potatp		: '🍓',
			eggplant			: '🍆',
			tomato				: '🍅',
//			corn				: '🍅',


			clock1 				: '🕐',
			clock10 			: '🕙',

	};


	Emoji.prototype.processLine = function( aLineIn ) {

		var textIn  = aLineIn;
		var textOut = '';
		var matches = [];

		while ( matches = textIn.match( /^(.*?)\ \:(\S*?)\:\ (.*)$/ ) ) {	// :emoji:
			var emoji = this.emojis[ matches[ 2 ] ];
			if ( emoji ) {
				textOut += matches[ 1 ] + emoji;
				textIn   = matches[ 3 ];
			} else {
				textOut += matches[ 1 ] + ' EMOJI ';
				textIn   = matches[ 3 ];
			}
		}

		return( textOut + textIn );

	}


	ktmd.readyExtension( 'emoji', new Emoji() );
